export const hard_topics = [
  // Philosophy, Ethics, and Existential Questions
  "life after death",
  "the existence of God",
  "free will",
  "the nature of consciousness",
  "the meaning of life",
  "the nature of reality",
  "ethics of AI",
  "existentialism",
  "the purpose of suffering",
  "determinism vs. free will",
  "the concept of nothingness",
  "morality",
  "justice",
  "fate vs. destiny",
  "the pursuit of happiness",
  "the nature of good and evil",
  "the power of belief",
  "personal identity",
  "reincarnation",
  "the philosophy of science",
  
  // Science, Technology, and the Universe
  "artificial intelligence",
  "quantum mechanics",
  "the origins of the universe",
  "time travel",
  "the possibility of a simulation",
  "space exploration",
  "the ethics of genetic engineering",
  "multiverse theory",
  "the concept of time",
  "global warming",
  "the singularity",
  "virtual reality",
  "the role of technology in society",
  "chaos theory",
  "evolution",
  "dark matter",
  "the survival of humanity",
  "the mysteries of black holes",
  "cybersecurity and privacy",
  
  // History, Wars, and Civilizations
  "the history of World War I",
  "the history of World War II",
  "the impact of the Cold War",
  "the fall of the Roman Empire",
  "the rise of ancient Greece",
  "the Industrial Revolution",
  "the age of exploration",
  "the history of colonialism",
  "the Crusades",
  "the history of the Ottoman Empire",
  "the Enlightenment",
  "the impact of the French Revolution",
  "the Vietnam War",
  "the history of the British Empire",
  "the American Civil War",
  "the formation of the United Nations",
  "the Renaissance",
  "the Russian Revolution",
  "the Space Race",
  "the fall of the Berlin Wall",
  
  // Geography, Geology, and Natural Formations
  "mountain formations",
  "volcanoes and lava flows",
  "tectonic plate shifts",
  "the Grand Canyon",
  "the Great Barrier Reef",
  "the formation of deserts",
  "the Amazon rainforest",
  "the Himalayas",
  "cave systems and stalactites",
  "geological time scales",
  "ocean currents and tides",
  "the formation of rivers",
  "erosion and weathering",
  "rock types: igneous, sedimentary, metamorphic",
  "ice ages and glacial formations",
  "the structure of the Earth's core",
  "the Mariana Trench",
  "continental drift",
  "tsunamis and seismic activity",
  "the role of water in shaping landscapes",
  
  // Art, Literature, and Music
  "the impact of Renaissance art",
  "the evolution of modern art",
  "the works of Vincent van Gogh",
  "the influence of Pablo Picasso",
  "the development of classical music",
  "the history of jazz",
  "the significance of Shakespeare's works",
  "the Romantic era in literature",
  "the evolution of cinema",
  "the influence of Impressionism",
  "the Golden Age of Hollywood",
  "the role of surrealism in art",
  "the history of sculpture",
  "the development of opera",
  "the works of Beethoven",
  "the impact of the printing press",
  "the Harlem Renaissance",
  "the history of photography",
  "the Baroque period",
  "the role of street art in modern society",
  
  // Cultures, Traditions, and Global Customs
  "Greek dishes and culinary traditions",
  "Japanese tea ceremonies",
  "social decorum in Victorian England",
  "the history of samurai culture",
  "Indian festivals like Diwali",
  "the cultural significance of martial arts",
  "the role of the griot in African culture",
  "the Maori traditions of New Zealand",
  "the Day of the Dead in Mexican culture",
  "the symbolism of totem poles",
  "the history of the Silk Road",
  "the cultural impact of the Viking age",
  "Egyptian burial customs",
  "the role of storytelling in Native American culture",
  "the art of flamenco dancing",
  "the influence of Confucianism on Chinese culture",
  "Brazilian Carnival",
  "the significance of the Hajj in Islam",
  "the impact of colonialism on indigenous cultures",
  "the role of ancestor worship in various cultures",
  
  // Psychology, Emotions, and Human Nature
  "the psychology of fear",
  "human decision-making",
  "the nature of love",
  "the role of emotions in shaping identity",
  "the impact of trauma on mental health",
  "the psychology of groupthink",
  "the pursuit of self-actualization",
  "the power of empathy",
  "social anxiety and its causes",
  "the concept of self-esteem",
  "the influence of childhood experiences on personality",
  "the science of memory",
  "the role of dreams in the subconscious",
  "the psychology of addiction",
  "the impact of social media on human interaction",
  "the relationship between emotion and reason",
  "the influence of culture on personality",
  "the role of nature vs. nurture in development",
  "the impact of isolation on the human psyche",
  "the science of happiness",
  
  // Politics, Governance, and Society
  "the role of democracy in modern society",
  "the balance of power between nations",
  "the impact of globalization",
  "the ethics of surveillance",
  "the future of capitalism",
  "the rise of authoritarianism",
  "social justice movements",
  "the role of education in society",
  "the impact of economic inequality",
  "the concept of universal basic income",
  "the future of work in a post-AI world",
  "the influence of lobbying in politics",
  "the ethics of media censorship",
  "the role of government in managing climate change",
  "the impact of political corruption",
  "the rise of populism",
  "the impact of digital misinformation",
  "the ethics of immigration policies",
  "the future of international relations",
  "the concept of human rights",
  
  // Futuristic, Sci-Fi, and Technological Speculation
  "the colonization of Mars",
  "the future of space travel",
  "the ethics of mind uploading",
  "the possibility of interstellar travel",
  "the rise of transhumanism",
  "the development of quantum computing",
  "the ethics of AI companions",
  "the future of human augmentation",
  "the impact of AI on creativity",
  "the possibility of alien contact",
  "the ethics of cloning",
  "the future of robotics in healthcare",
  "the concept of digital immortality",
  "the rise of smart cities",
  "the ethics of gene editing in humans",
  "the future of personal privacy in a digital age",
  "the impact of blockchain on society",
  "the role of AI in warfare",
  "the ethics of autonomous weapons",
  "the future of virtual reality and human interaction",
  
  // Religion, Spirituality, and Belief Systems
  "the purpose of religion in society",
  "the history of Buddhism",
  "the rise of atheism",
  "the impact of the Protestant Reformation",
  "the significance of Hinduism",
  "the evolution of Christianity",
  "the role of mysticism in spiritual practices",
  "the concept of karma",
  "the history of religious conflict",
  "the impact of the Enlightenment on religious thought",
  "the role of Shintoism in Japanese culture",
  "the ethics of proselytism",
  "the relationship between science and religion",
  "the significance of religious pilgrimages",
  "the history of the Islamic Golden Age",
  "the future of organized religion",
  "the role of faith in personal identity",
  "the cultural impact of the Catholic Church",
  "the spread of religion through colonization",
  "the rise of new religious movements",
  
  // Miscellaneous Thought-Provoking Topics
  "the ethics of space colonization",
  "the future of human relationships",
  "the psychology of nostalgia",
  "the ethics of animal testing",
  "the role of sports in society",
  "the impact of pandemics on global history",
  "the concept of fame and its impact on individuals",
  "the rise of megacities",
  "the future of public transportation",
  "the role of art in protest movements",
  "the influence of climate change on migration",
  "the impact of digital currencies",
  "the role of humor in coping with tragedy",
  "the future of human evolution",
  "the impact of tourism on local cultures",
  "the role of folklore in national identity",
  "the ethics of deepfake technology",
  "the significance of biodiversity",
  "the concept of freedom in a modern world",
  "the future of renewable energy"
];

export const easy_topics = [
  "What superpower would be the most fun for a teacher?",
  "What would happen if animals could speak?",
  "What would the world look like if gravity was half as strong?",
  "If you could change the color of the sky, what color would you choose and why?",
  "If time stopped for a day, what would you do?",
  "What would a society of robots value most?",
  "What would it be like if humans had wings?",
  "How would life be different if people could read minds?",
  "What would the perfect vacation look like?",
  "If plants could move, how would that change gardening?",
  "If you had to live in a cartoon world, which one would it be and why?",
  "What would your dream house look like if money wasn't an issue?",
  "If you could talk to one animal species, which would you choose and why?",
  "What kind of planet would you create if you were in charge?",
  "If clouds were solid, what would you build with them?",
  "What would be the first law you'd pass if you were the ruler of a new country?",
  "If humans hibernated, how would life change?",
  "What would a world be like if it had no oceans?",
  "If you could invent a new holiday, what would it celebrate?",
  "What would the world look like if trees could walk?",
  "If you could visit any fictional universe, which would you choose?",
  "What would it be like if everyone had the same job?",
  "How would society change if everyone lived to be 200 years old?",
  "If you could control one element (fire, water, earth, air), which would it be and why?",
  "What kind of weather would be perfect for you every day?",
  "If you could only wear one color for the rest of your life, which would you choose?",
  "What would life be like if people had to sleep for 24 hours straight once a week?",
  "If you could design a new animal, what would it look like?",
  "What would happen if there were no seasons?",
  "If you could make one food healthy forever, what would it be?",
  "What would the world look like if people could teleport anywhere instantly?",
  "What would life be like if humans had no sense of smell?",
  "If books could talk, what kind of stories would they tell?",
  "What kind of transportation would you invent for the future?",
  "What would your perfect city look like?",
  "If you could create a new sport, what would it be?",
  "If you could change one rule of physics, what would you change?",
  "What would a world look like where everyone could fly?",
  "If you could turn invisible for one day, what would you do?",
  "What would a world be like if nobody needed money?",
  "What would it be like if every building was made of glass?",
  "If you could make any object float, what would you choose?",
  "What would happen if people could breathe underwater?",
  "If you could shrink to the size of an ant for a day, what would you do?",
  "What kind of weather would you like to control?",
  "If you could live in any time period, which would you choose?",
  "What would happen if people could change their age at will?",
  "What would a perfect school day look like?",
  "If you could live in a video game world, which one would it be?",
  "If you could give one animal the ability to speak, which would it be?",
  "What would life be like if there were no mirrors?",
  "What would a city be like if it was always night?",
  "If you could swap places with any character in a book, who would it be?",
  "What kind of house would you build if there were no limitations?",
  "If the internet disappeared tomorrow, how would the world change?",
  "If you could breathe in space, what would you explore?",
  "If you could change your appearance at will, what would you look like?",
  "What would life be like if humans had tails?",
  "If you could have any non-magical superpower, what would it be?",
  "What would happen if all humans could live underwater?",
  "If you could talk to your past self, what advice would you give?",
  "If you could turn into any animal at will, which animal would it be?",
  "What would the world be like if there were no cars?",
  "If time travel was possible, where and when would you visit?",
  "What would happen if the moon was twice as large?",
  "If you could design a new planet, what would its most unique feature be?",
  "If everyone had to live in one giant city, what would that city look like?",
  "What would life be like if humans could never lie?",
  "If you could have any job for a day, what would it be?",
  "What would the world look like if humans lived in the sky?",
  "If you could instantly learn any skill, what would it be?",
  "What would a world without gravity be like?",
  "If all animals were friendly, which one would you want as a pet?",
  "What would happen if all water on Earth turned into soda?",
  "If you could turn any inanimate object into a living thing, what would it be?",
  "What would the world be like if everyone was always happy?",
  "If you could create a new language, what would it sound like?",
  "What would life be like if people could teleport to other planets?",
  "If you could make one law that everyone had to follow, what would it be?",
  "What would happen if the sun never set?",
  "If everyone could see in the dark, how would that change life?",
  "What kind of vehicle would you design if it could travel through both land and water?",
  "What would happen if trees could communicate?",
  "If you could only eat one food for the rest of your life, what would it be?",
  "What would life be like if people could only talk in rhymes?",
  "If you could create a new holiday, what would it celebrate?",
  "What would happen if time could be paused?",
  "If you could invent a new instrument, what would it sound like?",
  "What would the world be like if all humans had photographic memories?",
  "If you could choose one fictional character to come to life, who would it be?",
  "What would life be like if people could only communicate through singing?",
  "What would happen if everyone could control the weather?",
  "If animals ruled the world, which species would be in charge?",
  "What would a world look like where everyone had super speed?",
  "If you could design your own clothing line, what would it focus on?",
  "What would life be like if humans didn’t need to sleep?",
  "If you could control any one thing, what would it be?",
  "What would the world be like if everyone could walk through walls?",
  "If you could live in any mythical world, which one would it be?",
  "What would happen if all the oceans turned into land?",
  "If everyone lived in treehouses, how would that change daily life?",
  "What kind of building would you live in if there were no limits?",
  "If you could control when and where it rains, what would you do?",
  "What would life be like if people could see the future?",
  "If the earth had two moons, what would be different?",
  "What would a city look like if it floated on water?",
  "If you could travel anywhere in the universe instantly, where would you go?",
  "What would happen if everyone had to live in underground cities?",
  "If you could turn any piece of furniture into a robot, what would it be?",
  "What would a world be like if everyone had a twin?",
  "If you could have any mythical creature as a pet, which would it be?",
  "What would life be like if humans had an extra sense?",
  "If clouds were edible, what would they taste like?",
  "If you could make one extinct animal come back to life, which would it be?",
  "What would happen if the world was always covered in snow?",
  "If you could create a theme park, what would its theme be?",
  "What would life be like if people could talk to machines?",
  "If you could build a city underwater, what would it look like?",
  "What would happen if everyone could change their appearance at will?",
  "If you could have any non-human ability, what would it be?",
  "What would life be like if everyone could fly but only at night?",
  "If you could live on any other planet, which would it be and why?",
  "What would happen if everyone could see through walls?",
  "If humans could change their size at will, how would that change society?",
  "What would a world be like if people lived in floating cities?",
  "If you could swap bodies with any animal for a day, which animal would it be?",
  "What would life be like if there was no such thing as hunger?",
  "If you could only communicate with pictures, what would that be like?",
  "What would happen if people could control time in small increments?",
  "If you could live anywhere in the solar system, where would it be?",
  "What would the world be like if everyone had super strength?",
  "If you could erase one invention from history, what would it be?",
  "What would a world be like if every day lasted a year?",
  "If you could design a new species of plant, what would it look like?",
  "What would happen if everyone could control their dreams?",
  "If you could make one planet habitable, which would it be?",
  "What would life be like if people never aged?",
  "If you could combine any two animals into one, what would you create?",
  "What would happen if the world’s water supply was unlimited?",
  "If you could create a new kind of transportation, what would it be?",
  "What would life be like if humans could regenerate body parts?",
  "If you could invent a new mode of transportation, what would it be?",
  "What would happen if people could only speak one word per hour?",
  "If you could have any job in the future, what would it be?",
  "What would a world be like if nobody ever got sick?",
  "If you could create any weather phenomenon, what would it be?"
];
