export const hard_topics = [
  // Philosophy, Ethics, and Existential Questions
  "life after death",
  "the existence of God",
  "free will",
  "the nature of consciousness",
  "the meaning of life",
  "the nature of reality",
  "ethics of AI",
  "existentialism",
  "the purpose of suffering",
  "determinism vs. free will",
  "the concept of nothingness",
  "morality",
  "justice",
  "fate vs. destiny",
  "the pursuit of happiness",
  "the nature of good and evil",
  "the power of belief",
  "personal identity",
  "reincarnation",
  "the philosophy of science",
  
  // Science, Technology, and the Universe
  "artificial intelligence",
  "quantum mechanics",
  "the origins of the universe",
  "time travel",
  "the possibility of a simulation",
  "space exploration",
  "the ethics of genetic engineering",
  "multiverse theory",
  "the concept of time",
  "global warming",
  "the singularity",
  "virtual reality",
  "the role of technology in society",
  "chaos theory",
  "evolution",
  "dark matter",
  "the survival of humanity",
  "the mysteries of black holes",
  "cybersecurity and privacy",
  
  // History, Wars, and Civilizations
  "the history of World War I",
  "the history of World War II",
  "the impact of the Cold War",
  "the fall of the Roman Empire",
  "the rise of ancient Greece",
  "the Industrial Revolution",
  "the age of exploration",
  "the history of colonialism",
  "the Crusades",
  "the history of the Ottoman Empire",
  "the Enlightenment",
  "the impact of the French Revolution",
  "the Vietnam War",
  "the history of the British Empire",
  "the American Civil War",
  "the formation of the United Nations",
  "the Renaissance",
  "the Russian Revolution",
  "the Space Race",
  "the fall of the Berlin Wall",
  
  // Geography, Geology, and Natural Formations
  "mountain formations",
  "volcanoes and lava flows",
  "tectonic plate shifts",
  "the Grand Canyon",
  "the Great Barrier Reef",
  "the formation of deserts",
  "the Amazon rainforest",
  "the Himalayas",
  "cave systems and stalactites",
  "geological time scales",
  "ocean currents and tides",
  "the formation of rivers",
  "erosion and weathering",
  "rock types: igneous, sedimentary, metamorphic",
  "ice ages and glacial formations",
  "the structure of the Earth's core",
  "the Mariana Trench",
  "continental drift",
  "tsunamis and seismic activity",
  "the role of water in shaping landscapes",
  
  // Art, Literature, and Music
  "the impact of Renaissance art",
  "the evolution of modern art",
  "the works of Vincent van Gogh",
  "the influence of Pablo Picasso",
  "the development of classical music",
  "the history of jazz",
  "the significance of Shakespeare's works",
  "the Romantic era in literature",
  "the evolution of cinema",
  "the influence of Impressionism",
  "the Golden Age of Hollywood",
  "the role of surrealism in art",
  "the history of sculpture",
  "the development of opera",
  "the works of Beethoven",
  "the impact of the printing press",
  "the Harlem Renaissance",
  "the history of photography",
  "the Baroque period",
  "the role of street art in modern society",
  
  // Cultures, Traditions, and Global Customs
  "Greek dishes and culinary traditions",
  "Japanese tea ceremonies",
  "social decorum in Victorian England",
  "the history of samurai culture",
  "Indian festivals like Diwali",
  "the cultural significance of martial arts",
  "the role of the griot in African culture",
  "the Maori traditions of New Zealand",
  "the Day of the Dead in Mexican culture",
  "the symbolism of totem poles",
  "the history of the Silk Road",
  "the cultural impact of the Viking age",
  "Egyptian burial customs",
  "the role of storytelling in Native American culture",
  "the art of flamenco dancing",
  "the influence of Confucianism on Chinese culture",
  "Brazilian Carnival",
  "the significance of the Hajj in Islam",
  "the impact of colonialism on indigenous cultures",
  "the role of ancestor worship in various cultures",
  
  // Psychology, Emotions, and Human Nature
  "the psychology of fear",
  "human decision-making",
  "the nature of love",
  "the role of emotions in shaping identity",
  "the impact of trauma on mental health",
  "the psychology of groupthink",
  "the pursuit of self-actualization",
  "the power of empathy",
  "social anxiety and its causes",
  "the concept of self-esteem",
  "the influence of childhood experiences on personality",
  "the science of memory",
  "the role of dreams in the subconscious",
  "the psychology of addiction",
  "the impact of social media on human interaction",
  "the relationship between emotion and reason",
  "the influence of culture on personality",
  "the role of nature vs. nurture in development",
  "the impact of isolation on the human psyche",
  "the science of happiness",
  
  // Politics, Governance, and Society
  "the role of democracy in modern society",
  "the balance of power between nations",
  "the impact of globalization",
  "the ethics of surveillance",
  "the future of capitalism",
  "the rise of authoritarianism",
  "social justice movements",
  "the role of education in society",
  "the impact of economic inequality",
  "the concept of universal basic income",
  "the future of work in a post-AI world",
  "the influence of lobbying in politics",
  "the ethics of media censorship",
  "the role of government in managing climate change",
  "the impact of political corruption",
  "the rise of populism",
  "the impact of digital misinformation",
  "the ethics of immigration policies",
  "the future of international relations",
  "the concept of human rights",
  
  // Futuristic, Sci-Fi, and Technological Speculation
  "the colonization of Mars",
  "the future of space travel",
  "the ethics of mind uploading",
  "the possibility of interstellar travel",
  "the rise of transhumanism",
  "the development of quantum computing",
  "the ethics of AI companions",
  "the future of human augmentation",
  "the impact of AI on creativity",
  "the possibility of alien contact",
  "the ethics of cloning",
  "the future of robotics in healthcare",
  "the concept of digital immortality",
  "the rise of smart cities",
  "the ethics of gene editing in humans",
  "the future of personal privacy in a digital age",
  "the impact of blockchain on society",
  "the role of AI in warfare",
  "the ethics of autonomous weapons",
  "the future of virtual reality and human interaction",
  
  // Religion, Spirituality, and Belief Systems
  "the purpose of religion in society",
  "the history of Buddhism",
  "the rise of atheism",
  "the impact of the Protestant Reformation",
  "the significance of Hinduism",
  "the evolution of Christianity",
  "the role of mysticism in spiritual practices",
  "the concept of karma",
  "the history of religious conflict",
  "the impact of the Enlightenment on religious thought",
  "the role of Shintoism in Japanese culture",
  "the ethics of proselytism",
  "the relationship between science and religion",
  "the significance of religious pilgrimages",
  "the history of the Islamic Golden Age",
  "the future of organized religion",
  "the role of faith in personal identity",
  "the cultural impact of the Catholic Church",
  "the spread of religion through colonization",
  "the rise of new religious movements",
  
  // Miscellaneous Thought-Provoking Topics
  "the ethics of space colonization",
  "the future of human relationships",
  "the psychology of nostalgia",
  "the ethics of animal testing",
  "the role of sports in society",
  "the impact of pandemics on global history",
  "the concept of fame and its impact on individuals",
  "the rise of megacities",
  "the future of public transportation",
  "the role of art in protest movements",
  "the influence of climate change on migration",
  "the impact of digital currencies",
  "the role of humor in coping with tragedy",
  "the future of human evolution",
  "the impact of tourism on local cultures",
  "the role of folklore in national identity",
  "the ethics of deepfake technology",
  "the significance of biodiversity",
  "the concept of freedom in a modern world",
  "the future of renewable energy"
];

export const easy_topics = [
  "What superpower would be the most fun for a teacher?",
  "What would happen if animals could speak?",
  "What would the world look like if gravity was half as strong?",
  "If you could change the color of the sky, what color would you choose and why?",
  "If time stopped for a day, what would you do?",
  "What would a society of robots value most?",
  "What would it be like if humans had wings?",
  "How would life be different if people could read minds?",
  "What would the perfect vacation look like?",
  "If plants could move, how would that change gardening?",
  "If you had to live in a cartoon world, which one would it be and why?",
  "What would your dream house look like if money wasn't an issue?",
  "If you could talk to one animal species, which would you choose and why?",
  "What kind of planet would you create if you were in charge?",
  "If clouds were solid, what would you build with them?",
  "What would be the first law you'd pass if you were the ruler of a new country?",
  "If humans hibernated, how would life change?",
  "What would a world be like if it had no oceans?",
  "If you could invent a new holiday, what would it celebrate?",
  "What would the world look like if trees could walk?",
  "If you could visit any fictional universe, which would you choose?",
  "What would it be like if everyone had the same job?",
  "How would society change if everyone lived to be 200 years old?",
  "If you could control one element (fire, water, earth, air), which would it be and why?",
  "What kind of weather would be perfect for you every day?",
  "If you could only wear one color for the rest of your life, which would you choose?",
  "What would life be like if people had to sleep for 24 hours straight once a week?",
  "If you could design a new animal, what would it look like?",
  "What would happen if there were no seasons?",
  "If you could make one food healthy forever, what would it be?",
  "What would the world look like if people could teleport anywhere instantly?",
  "What would life be like if humans had no sense of smell?",
  "What would your perfect city look like?",
  "If you could create a new sport, what would it be?",
  "If you could change one rule of physics, what would you change?",
  "What would a world look like where everyone could fly?",
  "If you could turn invisible for one day, what would you do?",
  "What would a world be like if nobody needed money?",
  "What would it be like if every building was made of glass?",
  "If you could make any object float, what would you choose?",
  "What would happen if people could breathe underwater?",
  "If you could shrink to the size of an ant for a day, what would you do?",
  "What kind of weather would you like to control?",
  "If you could live in any time period, which would you choose?",
  "If you could live in a video game world, which one would it be?",
  "If you could give one animal the ability to speak, which would it be?",
  "What would life be like if there were no mirrors?",
  "What would a city be like if it was always night?",
  "If you could swap places with any character in a book, who would it be?",
  "What kind of house would you build if there were no limitations?",
  "If the internet disappeared tomorrow, how would the world change?",
  "If you could breathe in space, what would you explore?",
  "If you could change your appearance at will, what would you look like?",
  "What would life be like if humans had tails?",
  "If you could have any non-magical superpower, what would it be?",
  "What would happen if all humans could live underwater?",
  "If you could talk to your past self, what advice would you give?",
  "If you could turn into any animal at will, which animal would it be?",
  "What would the world be like if there were no cars?",
  "If time travel was possible, where and when would you visit?",
  "What would happen if the moon was twice as large?",
  "If you could design a new planet, what would its most unique feature be?",
  "If everyone had to live in one giant city, what would that city look like?",
  "What would life be like if humans could never lie?",
  "If you could have any job for a day, what would it be?",
  "What would the world look like if humans lived in the sky?",
  "If you could instantly learn any skill, what would it be?",
  "What would a world without gravity be like?",
  "If all animals were friendly, which one would you want as a pet?",
  "What would happen if all water on Earth turned into soda?",
  "If you could turn any inanimate object into a living thing, what would it be?",
  "What would the world be like if everyone was always happy?",
  "If you could create a new language, what would it sound like?",
  "What would life be like if people could teleport to other planets?",
  "If you could make one law that everyone had to follow, what would it be?",
  "What would happen if the sun never set?",
  "If everyone could see in the dark, how would that change life?",
  "What kind of vehicle would you design if it could travel through both land and water?",
  "What would happen if trees could communicate?",
  "If you could only eat one food for the rest of your life, what would it be?",
  "What would life be like if people could only talk in rhymes?",
  "If you could create a new holiday, what would it celebrate?",
  "What would happen if time could be paused?",
  "If you could invent a new instrument, what would it sound like?",
  "What would the world be like if all humans had photographic memories?",
  "If you could choose one fictional character to come to life, who would it be?",
  "What would life be like if people could only communicate through singing?",
  "What would happen if everyone could control the weather?",
  "If animals ruled the world, which species would be in charge?",
  "What would a world look like where everyone had super speed?",
  "If you could design your own clothing line, what would it focus on?",
  "What would life be like if humans didn’t need to sleep?",
  "If you could control any one thing, what would it be?",
  "What would the world be like if everyone could walk through walls?",
  "If you could live in any mythical world, which one would it be?",
  "What would happen if all the oceans turned into land?",
  "If everyone lived in treehouses, how would that change daily life?",
  "What kind of building would you live in if there were no limits?",
  "If you could control when and where it rains, what would you do?",
  "What would life be like if people could see the future?",
  "If the earth had two moons, what would be different?",
  "What would a city look like if it floated on water?",
  "If you could travel anywhere in the universe instantly, where would you go?",
  "What would happen if everyone had to live in underground cities?",
  "If you could turn any piece of furniture into a robot, what would it be?",
  "What would a world be like if everyone had a twin?",
  "If you could have any mythical creature as a pet, which would it be?",
  "What would life be like if humans had an extra sense?",
  "If clouds were edible, what would they taste like?",
  "If you could make one extinct animal come back to life, which would it be?",
  "What would happen if the world was always covered in snow?",
  "If you could create a theme park, what would its theme be?",
  "What would life be like if people could talk to machines?",
  "If you could build a city underwater, what would it look like?",
  "What would happen if everyone could change their appearance at will?",
  "If you could have any non-human ability, what would it be?",
  "What would life be like if everyone could fly but only at night?",
  "If you could live on any other planet, which would it be and why?",
  "What would happen if everyone could see through walls?",
  "If humans could change their size at will, how would that change society?",
  "What would a world be like if people lived in floating cities?",
  "If you could swap bodies with any animal for a day, which animal would it be?",
  "What would life be like if there was no such thing as hunger?",
  "If you could only communicate with pictures, what would that be like?",
  "What would happen if people could control time in small increments?",
  "If you could live anywhere in the solar system, where would it be?",
  "What would the world be like if everyone had super strength?",
  "If you could erase one invention from history, what would it be?",
  "What would a world be like if every day lasted a year?",
  "If you could design a new species of plant, what would it look like?",
  "What would happen if everyone could control their dreams?",
  "If you could make one planet habitable, which would it be?",
  "What would life be like if people never aged?",
  "If you could combine any two animals into one, what would you create?",
  "What would happen if the world’s water supply was unlimited?",
  "If you could create a new kind of transportation, what would it be?",
  "What would life be like if humans could regenerate body parts?",
  "If you could invent a new mode of transportation, what would it be?",
  "What would happen if people could only speak one word per hour?",
  "If you could have any job in the future, what would it be?",
  "What would a world be like if nobody ever got sick?",
  "If you could create any weather phenomenon, what would it be?",
  "What would happen if dreams could be recorded and shared?",
  "If you could only eat food grown on another planet, what would it taste like?",
  "What would a world look like where no one ever felt pain?",
  "If you could shrink the sun to the size of a basketball, how would the solar system change?",
  "What would society look like if everyone could only live to age 50?",
  "If you could control the direction of the wind, what would you use it for?",
  "What would happen if every house was connected by underground tunnels?",
  "If music were visible, what would different genres look like?",
  "What would life be like if all buildings could move from place to place?",
  "If you could build your own planet, what would be its strangest feature?",
  "What would a world be like if all languages were replaced with a new universal language?",
  "If humans had no sense of time, how would the world change?",
  "What would happen if everyone could walk on water?",
  "If stars were as close as streetlights, what would the night sky look like?",
  "What would life be like if everyone could communicate with animals telepathically?",
  "If you could turn anything into gold, what would you transform first?",
  "What would a society look like if every person had to create their own job?",
  "If every object had its own consciousness, how would that change the world?",
  "What would happen if everyone had to grow their own food?",
  "If emotions had colors, how would the world around you look?",
  "What would the world be like if rain never fell but plants still grew?",
  "If every person lived on their own personal island, what would society be like?",
  "What would happen if gravity on Earth slowly disappeared over 100 years?",
  "If every tree could tell a story, what stories would they share?",
  "What would life be like if everyone could travel through time but only backwards?",
  "If you could visit the deepest part of the ocean, what would you hope to find?",
  "What would a world look like where people could morph into different animals?",
  "If you could speak to your future self, what advice would you ask for?",
  "What would happen if there were no boundaries between countries?",
  "If you could change the shape of Earth, what would you make it look like?",
  "What would life be like if people could erase memories at will?",
  "If every country had the same culture, what would that culture be like?",
  "What would a world be like if all money was replaced by a barter system?",
  "If you could grow a new kind of tree, what fruit would it bear?",
  "What would happen if people could predict every natural disaster?",
  "If you could bring a historical figure to life, who would it be and what would you ask them?",
  "What would a society look like where everyone had an identical twin?",
  "If space travel were as common as air travel, where would you go first?",
  "What would life be like if people communicated only through symbols?",
  "If there were no mirrors or reflections, how would people perceive themselves?",
  "What would happen if people could travel at the speed of light?",
  "If you could erase one emotion from human experience, what would it be?",
  "What would a city look like if it were designed by children?",
  "If every person had to switch lives with someone else for a year, how would society change?",
  "What would happen if there was only one city left on Earth?",
  "If you could create a new color that doesn’t exist, what would it look like?",
  "What would life be like if humans lived in floating bubbles in the atmosphere?",
  "If all animals became as intelligent as humans, how would the world change?",
  "What would happen if every building had its own personality?",
  "If every time you blinked, a year passed, how would you live your life?",
  "What would a world be like where people could only sleep for one hour a day?",
  "If people could transfer thoughts and feelings directly to each other, what would society look like?",
  "What would happen if all books were banned and storytelling was only oral?",
  "If humans could communicate through thought, what would conversations be like?",
  "What would life be like if all humans were telekinetic?",
  "If people lived in space colonies orbiting Earth, how would daily life be different?",
  "What would happen if everyone had the ability to make one wish come true?",
  "If humans could merge their consciousness with machines, what would society become?",
  "What would a world look like where every building was transparent?",
  "If people could fly without wings, how would cities change?",
  "What would life be like if people only aged when they were unhappy?",
  "If you could hear any sound from any place in the world, what would you listen to?",
  "What would happen if everyone could only walk in straight lines?",
  "If people could see sounds, what would they look like?",
  "What would life be like if there was no need for sleep?",
  "If humans could swim through the air like fish, how would the world change?",
  "What would happen if the concept of time disappeared completely?",
  "If every piece of technology stopped working for a week, how would society adapt?",
  "What would a world look like where there was no such thing as temperature?",
  "If people could move at the speed of their thoughts, how would life change?",
  "What would happen if every person could change their identity once in a lifetime?",
  "If people could only communicate through writing, how would society function?",
  "What would a world be like where everyone had to wear the same clothes?",
  "If people could only remember the last 24 hours, what would society look like?",
  "What would happen if every building had its own personality and mood?",
  "If people could physically travel into their favorite books, what adventures would they have?",
  "What would life be like if everyone could control their own lifespan?",
  "If every mountain could float in the sky, what would the landscape look like?",
  "What would life be like if everyone could only see in black and white?",
  "If people had to pay for time instead of money, how would the world change?",
  "What would happen if everyone could clone themselves?",
  "If every sound had a flavor, what would different noises taste like?",
  "What would life be like if humans were nocturnal and only awake at night?",
  "If you could rewrite history, which event would you change and how?",
  "What would a world look like where people never experienced sadness?",
  "If all humans were the same height, how would society adapt?",
  "What would happen if people could only eat food grown in the ocean?",
  "If buildings could grow like trees, what kinds of cities would exist?",
  "What would a world look like if everyone had three arms?",
  "If everyone could jump as high as a skyscraper, how would transportation change?",
  "What would happen if people could only speak the truth?",
  "If emotions could be traded like currency, how would that affect relationships?",
  "What would life be like if you could choose to relive any day over and over?",
  "If you could turn any hobby into a profession, what would it be?",
  "What would a world be like where it rained upside down?",
  "If people could communicate with plants, what would we learn?",
  "What would happen if every person had a guardian animal?",
  "If you could live inside any video game for a year, which would you choose?",
  "What would life be like if everyone could switch languages instantly?",
  "If everyone lived inside domes on floating islands, how would that change society?",
  "What would happen if the sky was made of glass?",
  "If all humans could stop time for 10 minutes a day, what would people use it for?",
  "What would a world look like where there were no rules or laws?",
  "If people could visit alternate dimensions, how would life be different?",
  "What would happen if everyone could rewind their lives by five minutes each day?",
  "If everyone had a personalized robot assistant, how would society change?",
  "What would life be like if people could read books just by touching them?",
  "If every step you took made a flower bloom, how would the world change?",
  "What would happen if everyone could only communicate through dance?",
  "If people could live forever but had to give up one human ability, what would it be?",
  "What would life be like if everyone could breathe fire?",
  "If you could teleport only once in your life, where would you go?",
  "What would happen if everyone had wings but couldn't fly?",
  "If every day started with a random challenge, how would life change?",
  "What would the world look like if houses were made out of living organisms?",
  "If you could bring any invention from the future to the present, what would it be?",
  "What would happen if humans could see every frequency of light?",
  "If everyone could instantly master one skill at birth, how would that shape society?",
  "What would life be like if people could turn objects into gold by touching them?",
  "If humans could regenerate like lizards, how would that change our medical systems?",
  "What would happen if people could control gravity in small areas?",
  "If every city had its own climate, how would that affect where people live?",
  "What would life be like if everyone could speak every language fluently?",
  "If the stars spelled out messages each night, what would they say?",
  "What would happen if everyone could walk on walls and ceilings?",
  "If every sound people made left a permanent visible trail, what would the world look like?",
  "What would life be like if people could only sleep during the day?",
  "If you could travel through time but only once, would you go to the past or future?",
  "What would happen if people never got tired or needed to rest?",
  "If everyone had to design their own unique form of transportation, what would it be?",
  "What would a world be like where everyone was telepathic?",
  "If people could blend in perfectly with their surroundings like chameleons, how would society change?"
];
